# Generated by Django 6.0.2 on 2026-02-09 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Kigali City', [('Nyarugenge', 'Nyarugenge'), ('Gasabo', 'Gasabo'), ('Kicukiro', 'Kicukiro')]), ('Eastern Province', [('Nyagatare', 'Nyagatare'), ('Gatsibo', 'Gatsibo'), ('Kayonza', 'Kayonza'), ('Rwamagana', 'Rwamagana'), ('Bugesera', 'Bugesera'), ('Ngoma', 'Ngoma'), ('Kirehe', 'Kirehe')]), ('Northern Province', [('Musanze', 'Musanze'), ('Burera', 'Burera'), ('Gicumbi', 'Gicumbi'), ('Rulindo', 'Rulindo'), ('Gakenke', 'Gakenke')]), ('Southern Province', [('Huye', 'Huye'), ('Nyamagabe', 'Nyamagabe'), ('Gisagara', 'Gisagara'), ('Nyanza', 'Nyanza'), ('Nyaruguru', 'Nyaruguru'), ('Muhanga', 'Muhanga'), ('Kamonyi', 'Kamonyi'), ('Ruhango', 'Ruhango')]), ('Western Province', [('Rubavu', 'Rubavu'), ('Rusizi', 'Rusizi'), ('Karongi', 'Karongi'), ('Nyabihu', 'Nyabihu'), ('Rutsiro', 'Rutsiro'), ('Ngororero', 'Ngororero'), ('Nyamasheke', 'Nyamasheke')])], default='Gasabo', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('TEMP', 'Temperature')], default='TEMP', max_length=10)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='farms.sensorreading')),
            ],
        ),
    ]
