# Generated by Django 6.0.2 on 2026-02-10 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message="Format: '+2507xxxxxxxx' or '07xxxxxxxx'. Must be a valid Rwanda mobile number.", regex='^\\+?2507[2389]\\d{7}$')]),
        ),
    ]
