# Generated by Django 6.0.2 on 2026-02-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_notificationpreference_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
